Word.destroy_all
Category.destroy_all

categories = [
  {name: "easy", points: 5},
  {name: "medium", points: 15},
  {name: "hard", points: 30}
]

categories.each { |category| Category.create(category) }

word_hash = [
  { wordname: "Airplane", category_id: 1},
  { wordname: "Ears", category_id: 1},
  { wordname: "Piano", category_id: 1},
  { wordname: "Angry", category_id: 1},
  { wordname: "Elephant", category_id: 1},
  { wordname: "Pinch", category_id: 1},
  { wordname: "Baby", category_id: 1},
  { wordname: "Fish", category_id: 1},
  { wordname: "Reach", category_id: 1},
  { wordname: "Ball", category_id: 1},
  { wordname: "Flick", category_id: 1},
  { wordname: "Remote", category_id: 1},
  { wordname: "Baseball", category_id: 1},
  { wordname: "Football", category_id: 1},
  { wordname: "Roll", category_id: 1},
  { wordname: "Hashketball", category_id: 1},
  { wordname: "Fork", category_id: 1},
  { wordname: "Bounce", category_id: 1},
  { wordname: "Giggle", category_id: 1},
  { wordname: "Scissors", category_id: 1},
  { wordname: "Cat", category_id: 1},
  { wordname: "Golf", category_id: 1},
  { wordname: "Skip", category_id: 1},
  { wordname: "Chicken", category_id: 1},
  { wordname: "Guitar", category_id: 1},
  { wordname: "Sneeze", category_id: 1},
  { wordname: "Chimpanzee", category_id: 1},
  { wordname: "Hammer", category_id: 1},
  { wordname: "Spin", category_id: 1},
  { wordname: "Clap", category_id: 1},
  { wordname: "Happy", category_id: 1},
  { wordname: "Spoon", category_id: 1},
  { wordname: "Cough", category_id: 1},
  { wordname: "Horns", category_id: 1},
  { wordname: "Stomp", category_id: 1},
  { wordname: "Cry", category_id: 1},
  { wordname: "Joke", category_id: 1},
  { wordname: "Stop", category_id: 1},
  { wordname: "Dog", category_id: 1},
  { wordname: "Mime", category_id: 1},
  { wordname: "Tail", category_id: 1},
  { wordname: "Drink", category_id: 1},
  { wordname: "Penguin", category_id: 1},
  { wordname: "Toothbrush", category_id: 1},
  { wordname: "Drums", category_id: 1},
  { wordname: "Phone", category_id: 1},
  { wordname: "Wiggle", category_id: 1},
  { wordname: "Duck", category_id: 1},
  { wordname: "Photographer", category_id: 1},
  { wordname: "Archer", category_id: 2 },
  { wordname: "Ghost", category_id: 2 },
  { wordname: "Rock star", category_id: 2 },
  { wordname: "Balance beam", category_id: 2 },
  { wordname: "Haircut", category_id: 2 },
  { wordname: "Shoelaces", category_id: 2 },
  { wordname: "Ballet", category_id: 2 },
  { wordname: "Halo", category_id: 2 },
  { wordname: "Sick", category_id: 2 },
  { wordname: "Balloon", category_id: 2 },
  { wordname: "Hiccup", category_id: 2 },
  { wordname: "Singer", category_id: 2 },
  { wordname: "Banana peel", category_id: 2 },
  { wordname: "Hot dog", category_id: 2 },
  { wordname: "Skateboard", category_id: 2 },
  { wordname: "Book", category_id: 2 },
  { wordname: "Hungry", category_id: 2 },
  { wordname: "Slippery", category_id: 2 },
  { wordname: "Braces", category_id: 2 },
  { wordname: "Hurt", category_id: 2 },
  { wordname: "Soccer", category_id: 2 },
  { wordname: "Button", category_id: 2 },
  { wordname: "Ice skating", category_id: 2 },
  { wordname: "Strong", category_id: 2 },
  { wordname: "Car", category_id: 2 },
  { wordname: "Karate", category_id: 2 },
  { wordname: "Stubbed toe", category_id: 2 },
  { wordname: "Cheers", category_id: 2 },
  { wordname: "Ladder", category_id: 2 },
  { wordname: "Sunshine", category_id: 2 },
  { wordname: "Clown", category_id: 2 },
  { wordname: "Light bulb", category_id: 2 },
  { wordname: "Surprise", category_id: 2 },
  { wordname: "Dinosaur", category_id: 2 },
  { wordname: "Limbo", category_id: 2 },
  { wordname: "Swing", category_id: 2 },
  { wordname: "Disco", category_id: 2 },
  { wordname: "Macarena", category_id: 2 },
  { wordname: "Sword", category_id: 2 },
  { wordname: "Dizzy", category_id: 2 },
  { wordname: "Paint", category_id: 2 },
  { wordname: "Tap dance", category_id: 2 },
  { wordname: "Fart", category_id: 2 },
  { wordname: "Pirate", category_id: 2 },
  { wordname: "Wheelbarrow", category_id: 2 },
  { wordname: "Fishing", category_id: 2 },
  { wordname: "Read", category_id: 2 },
  { wordname: "Wizard of Oz", category_id: 2 },
  { wordname: "Gallop", category_id: 2 },
  { wordname: "River dance", category_id: 2 },
  { wordname: "Birthday ", category_id: 3 },
  { wordname: "Hedgehog", category_id: 3 },
  { wordname: "Pizza", category_id: 3 },
  { wordname: "Blanket", category_id: 3 },
  { wordname: "Helicopter", category_id: 3 },
  { wordname: "President", category_id: 3 },
  { wordname: "Bright", category_id: 3 },
  { wordname: "Hurricane", category_id: 3 },
  { wordname: "Rainbow", category_id: 3 },
  { wordname: "Bump", category_id: 3 },
  { wordname: "Kite", category_id: 3 },
  { wordname: "Rollercoaster", category_id: 3 },
  { wordname: "Christmas", category_id: 3 },
  { wordname: "Light", category_id: 3 },
  { wordname: "Shadow", category_id: 3 },
  { wordname: "Coffee", category_id: 3 },
  { wordname: "Magic", category_id: 3 },
  { wordname: "Shopping", category_id: 3 },
  { wordname: "Cradle", category_id: 3 },
  { wordname: "Makeup", category_id: 3 },
  { wordname: "Shuffle", category_id: 3 },
  { wordname: "Deer", category_id: 3 },
  { wordname: "Marriage", category_id: 3 },
  { wordname: "Slice", category_id: 3 },
  { wordname: "Drool", category_id: 3 },
  { wordname: "Mash", category_id: 3 },
  { wordname: "Slip n’ slide", category_id: 3 },
  { wordname: "Electric Slide", category_id: 3 },
  { wordname: "Measure", category_id: 3 },
  { wordname: "Smear", category_id: 3 },
  { wordname: "Excitement", category_id: 3 },
  { wordname: "Mirror", category_id: 3 },
  { wordname: "Spider", category_id: 3 },
  { wordname: "Fight Club", category_id: 3 },
  { wordname: "Monster", category_id: 3 },
  { wordname: "The Lion King", category_id: 3 },
  { wordname: "Firefighter", category_id: 3 },
  { wordname: "Motorcycle", category_id: 3 },
  { wordname: "Trampoline", category_id: 3 },
  { wordname: "Flashlight", category_id: 3 },
  { wordname: "Nightmare", category_id: 3 },
  { wordname: "Waterfall", category_id: 3 },
  { wordname: "Garden", category_id: 3 },
  { wordname: "Nosey", category_id: 3 },
  { wordname: "Window", category_id: 3 },
  { wordname: "Giraffe", category_id: 3 },
  { wordname: "Overwhelmed", category_id: 3 },
  { wordname: "Yo-yo", category_id: 3 },
  { wordname: "Heavy", category_id: 3 },
  { wordname: "Pancakes", category_id: 3 }
]

word_hash.each { |word| Word.create(word) }

puts "I have been seededed."
